#+hugo_base_dir: ../

* TODO GPGME++ 简明使用指南
:PROPERTIES:
:EXPORT_HUGO_SECTION: zh-cn/posts
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_BUNDLE: gpgmepp-usage
:EXPORT_DRAFT: false
:EXPORT_HUGO_PAIRED_SHORTCODES: alert
:END:


#+attr_shortcode: :icon bell :iconColor white :cardColor #CC7700
#+begin_alert
前置要求  \\
阅读本文前，建议您了解 OpenPGP 及 GnuPG 的基本用法，并具备 C++ 的基础编程能力。
#+end_alert

** GPGME++ 的基本介绍

*** GPGME 是什么？

“GnuPG Made Easy (GPGME) 是一个旨在让应用程序更容易访问 GnuPG 的库。它提供了一个用于加密 、解密、签名、签名验证和密钥管理的加密 API。目前它使用 GnuPG 的 OpenPGP 后端作为默认选项，但 API 并不限于这个引擎。”  \\
来源: [[https://www.gnupg.org/software/gpgme/index.html]]

GPGME 的目标是 “让应用程序更容易访问 GnuPG”，因此:
1. 它一离开 GnuPG 就是纸老虎，因为它本身只封装调用，真正的加解密全靠 GnuPG 后端。
2. 它 (在默认情况下) 会以 ~/.gnupg 为工作目录。
3. 它会调用 Pinentry (PIN码输入对话框) 输入解密密钥/访问智能卡的PIN。
4. 它在调用 OpenPGP 智能卡方面上遥遥领先 (绝大多数软件在这方面都依赖它/整个GnuPG体系)。

但 GPGME 并不是我们这篇文章论述的重点，我们要聊的是它的++版本。

*** 这个++版本又是什么？
GPGME++ (aka GPGMEPP) 就是 GPGME 的官方 C++ 绑定库，它的接口对于 C++ 比较友好，但仍保留有许多 C-style。  \\
因为它是 GPGME 的封装，故 GPGME 的特点它都有。  \\
接下来，我们就要用 GPGME++ 开始编码啦~

** 基础部分
#+attr_shortcode: :icon lightbulb :iconColor white :cardColor #0077DD
#+begin_alert
工欲善其事，必先利其器。  \\
要执行下面的代码，您的环境应当满足下列条件:
1. 安装 GnuPG 并在默认工作目录下有至少一对可用的公私钥。
2. 安装 GPGME 和 GPGME++ (部分发行版将 GPGME++ 集成在 GPGME 的主包中，请根据实际情况安装对应的开发包) 。
3. 有可用的 C++17 编译器。
#+end_alert

*** 加密与解密
现在我们看一个最简的加密解密流程——把 "Hello World!" 加密后再解密回来。  \\
请把代码中的指纹替换成你自己的密钥指纹（ =gpg -K= 是你的好帮手）。  \\
  \\
编译命令： 
#+begin_src bash
   g++ -std=gnu++17 basic_gpgmepp_encrypt_and_decrypt.cpp \
       -o basic_gpgmepp_encrypt_and_decrypt \
       `pkg-config --cflags --libs gpgmepp`
#+end_src


#+begin_src C++
  // Filename: basic_gpgmepp_encrypt_and_decrypt.cpp
  // SPDX-License-Identifier: Unlicense
  // This file is released into the public domain under the Unlicense.
  // See LICENSE or https://unlicense.org for details.
  
  #include <gpgme++/context.h> // 最基本的头文件（几乎包含所有操作）
  #include <gpgme++/key.h> // 管理与使用密钥的核心头文件
  #include <gpgme++/data.h> // 用于传入接收数据的数据结构头文件
  #include <gpgme++/encryptionresult.h> // 加密操作的返回值结构头文件
                                        // 每一个核心操作都需要导入对应的返回值结构头文件
  #include <gpgme++/decryptionresult.h> // 同理
  #include <iostream>
  #include <vector>

  int main() {
    GpgME::initializeLibrary(); // 初始化库，所有使用GPGME++的程序的必经之路
    // ctx的类型是std::unique_ptr<GpgME::Context>
    // ctx是最核心的对象，里面有我们接下来要用到的操作
    auto ctx = GpgME::Context::create(GpgME::Protocol::OpenPGP);
    //目的是让我们接下来的输出都ascii化，便于复制验证
    ctx->setArmor(true);
    std::string plaintext = "Hello World!";
    // 通过复制一段内存来构造GpgME::Data
    GpgME::Data in(plaintext.c_str(), plaintext.size());
    // 两个未初始化的GpgME::Data，可以由对应操作自动分配足够的内存
    GpgME::Data out1,out2;
    // 目前只是为了调用函数，后面会讲错误处理
    GpgME::Error e;
    // 通过指纹获取收件人密钥
    // 注意：解密能否成功，取决于 ~/.gnupg 中是否存在对应的私钥
    // 因此下面建议用你自己的密钥（公钥加密、私钥解密）来测试
    // 当然，如果没有获取到密钥，程序就gg了
    GpgME::Key key = ctx->key(/* Your key's fingerprint 千万不要忘记改 */, e);
    // 传入收件人列表和存储明文和密文的数据结构来加密
    // 返回值是 EncryptionResult，Error藏在里面，其他的操作同理，具体在错误处理部分讲解
    ctx->encrypt(std::vector{key}, in, out1, /* flag */ GpgME::Context::None);
    std::cout << "Ciphertext: \n" << out1.toString() << std::endl;
    // 传入存储密文和明文的数据结构来解密
    // 这个操作会自动查询工作目录下的私钥并匹配，不需要手动指定
    // 同时，如果密钥不能直接访问，则会调用pinentry来解密密钥/访问智能卡
    // 后面会讲由程序输入密码的解决方案
    ctx->decrypt(out1, out2);
    std::cout << "Plaintext: \n" << out2.toString() << std::endl;
    return 0;
  }
#+end_src
